# Generated by Django 2.0.4 on 2018-04-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_type', models.CharField(default='', max_length=16)),
                ('listing_title', models.CharField(default='', max_length=255)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(default='', max_length=255)),
                ('type_priority', models.BooleanField(default=False)),
                ('type_strict', models.BooleanField(default=False)),
                ('item_sex', models.CharField(default='', max_length=8)),
                ('sex_priority', models.BooleanField(default=False)),
                ('sex_strict', models.BooleanField(default=False)),
                ('item_brand', models.CharField(default='', max_length=255)),
                ('brand_priority', models.BooleanField(default=False)),
                ('brand_strict', models.BooleanField(default=False)),
                ('item_model', models.CharField(default='', max_length=255)),
                ('model_priority', models.BooleanField(default=False)),
                ('model_strict', models.BooleanField(default=False)),
                ('item_colour', models.CharField(default='', max_length=255)),
                ('colour_priority', models.BooleanField(default=False)),
                ('colour_strict', models.BooleanField(default=False)),
                ('item_condition', models.CharField(default='', max_length=64)),
                ('condition_priority', models.BooleanField(default=False)),
                ('condition_strict', models.BooleanField(default=False)),
                ('item_material', models.CharField(default='', max_length=64)),
                ('material_priority', models.BooleanField(default=False)),
                ('material_strict', models.BooleanField(default=False)),
                ('item_size', models.FloatField(default='0.0')),
                ('size_priority', models.BooleanField(default=False)),
                ('size_strict', models.BooleanField(default=False)),
                ('item_notes', models.TextField(default='No notes have been left!')),
                ('item_matching', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_listing_id', models.IntegerField()),
                ('matched_listing_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_rating', models.FloatField(default=0.0)),
                ('user_num_ratings', models.IntegerField(default=0.0)),
                ('user_banned', models.BooleanField(default=False)),
                ('user_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.Listing'),
        ),
    ]
