# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shoes/photos/')),
            ],
        ),
    ]
