# Generated by Django 2.0.4 on 2018-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='recent_buyings',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_sellings',
            field=models.CharField(default='', max_length=256),
        ),
    ]
