# Generated by Django 2.0.4 on 2018-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='listing_type',
            field=models.CharField(default='buying', max_length=12),
        ),
        migrations.AlterField(
            model_name='selling',
            name='listing_type',
            field=models.CharField(default='selling', max_length=12),
        ),
    ]
