# Generated by Django 2.0.4 on 2018-05-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.User'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.User'),
        ),
    ]
