# Generated by Django 2.0.4 on 2018-04-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.Listing')),
            ],
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='item_description',
            new_name='item_notes',
        ),
        migrations.AddField(
            model_name='spec',
            name='item_sex',
            field=models.CharField(default='unisex', max_length=6),
        ),
    ]
