# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0002_auto_20180404_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('listing_type', models.CharField(default='Unknown', max_length=16)),
                ('listing_title', models.CharField(default='Unknown', max_length=255)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(default='Unknown', max_length=255)),
                ('type_priority', models.BooleanField(default=False)),
                ('type_strict', models.BooleanField(default=False)),
                ('item_sex', models.CharField(default='Unknown', max_length=8)),
                ('sex_priority', models.BooleanField(default=False)),
                ('sex_strict', models.BooleanField(default=False)),
                ('item_brand', models.CharField(default='Unknown', max_length=255)),
                ('brand_priority', models.BooleanField(default=False)),
                ('brand_strict', models.BooleanField(default=False)),
                ('item_model', models.CharField(default='Unknown', max_length=255)),
                ('model_priority', models.BooleanField(default=False)),
                ('model_strict', models.BooleanField(default=False)),
                ('item_colour', models.CharField(default='Unknown', max_length=255)),
                ('colour_priority', models.BooleanField(default=False)),
                ('colour_strict', models.BooleanField(default=False)),
                ('priority_strict', models.BooleanField(default=False)),
                ('item_condition', models.CharField(default='Unknown', max_length=64)),
                ('condition_priority', models.BooleanField(default=False)),
                ('condition_strict', models.BooleanField(default=False)),
                ('item_material', models.CharField(default='Unknown', max_length=64)),
                ('material_priority', models.BooleanField(default=False)),
                ('material_strict', models.BooleanField(default=False)),
                ('item_size', models.FloatField(default='0.0')),
                ('size_priority', models.BooleanField(default=False)),
                ('size_strict', models.BooleanField(default=False)),
                ('item_notes', models.TextField(default='No notes have been left!')),
                ('item_matching', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_listing_id', models.IntegerField()),
                ('matched_listing_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('user_admin', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.User'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyjacs_app.Listing'),
        ),
    ]
