# Generated by Django 2.0.4 on 2018-05-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0002_auto_20180503_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='item_matching',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='item_matching',
            field=models.IntegerField(null=True),
        ),
    ]
