# Generated by Django 2.0.4 on 2018-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0002_auto_20180502_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='item_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='selling',
            name='item_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='buying',
            name='brand_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='colour_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='condition_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_colour',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_condition',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_material',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_sex',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='buying',
            name='item_size',
            field=models.FloatField(blank=True, default='0.0'),
        ),
        migrations.AlterField(
            model_name='buying',
            name='material_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='max_price',
            field=models.FloatField(blank=True, default=99999.0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='min_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='model_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='sex_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='size_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying',
            name='type_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
