# Generated by Django 2.0.4 on 2018-04-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0003_auto_20180406_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
    ]
