# Generated by Django 2.0.4 on 2018-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0005_auto_20180411_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='item_condition',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='spec',
            name='item_material',
            field=models.CharField(default='Plastic/Synthetic\t', max_length=64),
        ),
        migrations.AlterField(
            model_name='spec',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
    ]
