# Generated by Django 2.0.4 on 2018-04-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0006_auto_20180411_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='item_brand',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_condition',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_matching',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_material',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_model',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_notes',
            field=models.TextField(default='No notes have been left!'),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_sex',
            field=models.CharField(default='Unknown', max_length=8),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_size',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
