# Generated by Django 2.0.4 on 2018-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0007_auto_20180411_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_colour',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
