# Generated by Django 2.0.4 on 2018-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0008_listing_item_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='colour_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='material_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='material_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='model_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='model_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='priority_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='sex_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='sex_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='size_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='size_strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type_strict',
            field=models.BooleanField(default=False),
        ),
    ]
