# Generated by Django 2.0.4 on 2018-04-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0009_auto_20180411_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='priority_strict',
            new_name='colour_strict',
        ),
    ]
