# Generated by Django 2.0.4 on 2018-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyjacs_app', '0010_auto_20180412_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_brand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_colour',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_condition',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_material',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_sex',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
